package com.csc366.project.repository;

import com.csc366.project.entity.Supplier;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import org.springframework.data.jpa.repository.Query;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.repository.query.Param;

// This class will be automatically implemented by Spring and made available as a "Bean" named personRepository
@Repository
public interface SupplierRepository extends JpaRepository<Supplier, Long>{

    // query inferred from method name, code generated by Spring Framework
    Supplier findByName(String name);

    // JPQL query with join
    @Query("select s from Supplier s where s.address.street = :street")
    Supplier findByStreetJpql(@Param("street") String street);

    @Modifying
    @Query("update Supplier s set s.name = :newName where s.name = :oldName")
    void updateName(@Param("oldName") String oldName, @Param("newName") String newName);
}

